spring:
  profiles:
    default: http
  ai:
    mcp:
      server:
        name: scheduler-mcp-server
        version: 1.0.0
        instructions: "This mcp server provides tools to manager cron jobs"


logging.level.org.springframework.ai: DEBUG
logging.level.io.modelcontextprotocol: DEBUG